/*
 * File: app/view/home/MainV.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.define('Garigori.view.home.MainV', {
    extend: 'Ext.Container',
    alias: 'widget.homemainv',
     requires: ['Ext.List'],
    
    config: {
        layout: {
            type: 'vbox',
            
        },
        scrollable : "vertical",
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'GARIGORI',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'infoBtn',
                        iconAlign: 'right',
                        iconCls: 'info',
                        iconMask: true,
                        text: ''
                    }
                ]
            },{
            	html: '<div style="border-bottom: 1px solid #cf0012"><b style="font-size: 13px; color: #888888">FAVORITE</b></div>'
	        },{
            	xtype: 'coverflowv',
            	height: 150,
				//layout: (Ext.os.deviceType === 'Phone')? 'fit': {
				layout: {
					type: 'vbox',
					pack:'center',
					align: 'center'
				},
            },{
            	html: '<div style="border-bottom: 1px solid #cf0012"><b style="font-size: 13px; color: #888888">RECENT</b></div>'
	        }, {
                xtype: 'dataview',
                style: 'background-color:  eeeeee; padding-top: 10px',
                height: 150,
                scrollable: 'horizontal',
                inline: {
                    wrap: false
                },
                itemTpl: '<div style="margin: 0 5px 0 5px"><img src="{thumbnail}" style="-webkit-box-shadow: 2px 3px 3px #555555;"><div style="font-size: 10px;">노무회계사</div></div>',
                store : 'coverFlowS',
               	scrollable: {
					direction: 'horizontal',
					indicators: false,
					directionLock:true
				},
            },{
            	html: '<b style="font-size: 13px;">가장 많은 조회수</b>'
	        }, {
                xtype: 'dataview',
	            style: 'background-color:  eeeeee;',
	            height: 150,
	            scrollable: 'horizontal',
	            inline: {
	                wrap: false
	            },
	            itemTpl: '<div style="margin: 0 5px 0 5px"><img src="{thumbnail}" style="-webkit-box-shadow: 2px 3px 3px #555555;"><div style="font-size: 10px;">노무회계사</div></div>',
	            store : 'coverFlowS',
	            scrollable: {
					direction: 'horizontal',
					indicators: false,
					directionLock:true
				},
	        }
        ]
    }

});