/*
 * File: app/view/jobshare/DetailV.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Garigori.view.speaker.DetailV', {
    extend: 'Ext.Container',
    alias: 'widget.speakerdetailv',
    
    currentVideoId: null,

    config: {
        title: 'Speaker',
        layout: {
            type: 'hbox',
        },
        scrollable: {
            direction: 'vertical'
        },
        tpl: [
            '<table border="0" width="100%">',
            '<tr>',
            '	<td>{title}</td>',
            '	<td>',
            //'<div class="x-rating-star" id="favoriteMark"></div>',
            '<tpl if="isFavorite">',
            	'<div class="x-rating-star-hover" id="favoriteMark"></div>',
            '<tpl else>',
            	'<div class="x-rating-star" id="favoriteMark"></div>',
            '</tpl>',
            '</td>',
            '</tr>',
            '<tr>',
        	'	<td><img id="player" src="{thumbnail0}" width="320" height="180" alt="Garigori"></td>',
        	'	<td><button>facebook</button><button>twitter</button></td>',
        	'</tr>',
        	'<tr class=table_content>',
    		'	<td colspan="2">인터뷰내용</td>',
    		'</tr>',
    		'<tr>',
			'<td colspan="2">{content}</td>',
			'</tr>',
			'</table>',

        ],
        items: [
        ]
    },
	initialize: function() {
		this.callParent();
		// View에 event를 controller에 넘겨줌
		this.relayEvents(this.element, ['tap']);
	}
});